### PR TITLE
Correct Method Name in README.md

### PR DESCRIPTION
**Pull request by DevinNorgarb**

### CODE REVIEW

**Comment by jlamborn324** [comment]
merge this! 🙏🏻🙏🏻

**Comment by DevinNorgarb** [comment]
Hi @jlamborn324 & Maintainers. 
Any reason this has not been merged yet? :)

**Comment by DevinNorgarb** [comment]
Hello @jlamborn324

**Comment by jlamborn324** [comment]
Hello @DevinNorgarb, I am merely a bystander. My only power is to comment upon the things I see.  I have no power here!

**Comment by DevinNorgarb** [comment]
Sorry @jlamborn324. I think this project has a lot of potential. It is a pity that it is so quiet around here

**Comment by DevinNorgarb** [comment]
@haxzie

**Comment by DevinNorgarb** [comment]
Fix for #2

**Review by haxzie — APPROVED** [review]

**Pull request merged**
